### ISSUE TITLE
Image in Markdown file not rendering

### ISSUE THREAD

**Issue by Ertain** [klaussilveira/gitlist#807] opened 2018-07-29 00:44 UTC
In the README.md file of one of my repos, I have screenshots which are not being interpreted correctly. I'm using the code `![Screenshot](screenshot.jpg)`, yet that's not being converted into HTML. Both the image and the README.md file are in the same directory, btw.

**Comment by alehaa** [comment] 2018-07-29 15:08
I think this is a duplicate of #659.

**Closed by alehaa** 2018-07-29 15:08 UTC
