### ISSUE TITLE
Doesn't seem to be working on Windows

### ISSUE THREAD

**Issue by tobya** [klaussilveira/gitlist#511] opened 2014-09-07 11:35 UTC
I did some work a long time ago to get gitlist working in a simple fashion in windows.  I just came back to gitlist and again am having difficulty getting it to run on windows.

Has anyone else managed to get the latest version working on windows?  With Apache?

I would be interested in working with another php windows developer to get gitlist working reliably on windows.  Is anyone interested?

**Comment by garygreen** [comment] 2015-07-24 20:49
Duplicate of #574

**Closed by garygreen** 2015-07-24 20:49 UTC
