### ISSUE TITLE
Simple "Clone" Block wanted

### ISSUE THREAD

**Issue by eits-admin** [klaussilveira/gitlist#549] opened 2014-12-27 06:21 UTC
I would like a very simple "legend" block on the right side of the repo browser called:  "Clone Repo" with clone information configured in config.ini so the legend appears as a URL that I can copy/paste into my git client.

that way I don't have to remember my server information/path, etc.

Cool tool!  thanks for this!

**Comment by klaussilveira** [comment] 2015-02-06 15:53
Duplicate of: https://github.com/klaussilveira/gitlist/issues/205

**Closed by klaussilveira** 2015-02-06 15:53 UTC
