### ISSUE TITLE
Exception when Repository folder contains dot

### ISSUE THREAD

**Issue by RanaInside** [klaussilveira/gitlist#545] opened 2014-12-21 02:31 UTC
Version 0.3 Works fine;
tried Stable 0.5 and Beta version: both fails with following error:

Oops! An exception has been thrown during the rendering of a template ("Parameter "repo" for route "repository" must match " ... folder details removed " (" .removed.. " given) to generate a corresponding URL.") in "index.twig" at line 16.

Error is raised when my Repository folder contains "dot" ie: MyCompany.MyCoolComponent

Ps: Also it says "Powered by GitList 0.4.0"; shouldn't it display correct version;

**Comment by garygreen** [comment] 2015-07-24 20:42
Duplicate of #604

**Closed by garygreen** 2015-07-24 20:42 UTC
