### ISSUE TITLE
Move all public files out of main app

### ISSUE THREAD

**Issue by garygreen** [klaussilveira/gitlist#555] opened 2015-02-04 15:37 UTC
At the moment all the files exist in the main base app. Only the file `config.ini` is denied access by use of `.htaccess` file -- you can still access _everything_ else, including cache folder, vendor, tests, composer file etc, and if you use nginx you even have access to the config.ini out of the box.

I think it would make a lot of sense if all the publicly accessible files were moved into a separate folder `public` which you would set as the document root in your server config.

**Comment by indera** [comment] 2015-02-05 04:42
I installed gitlist on a mac in the "/Library/WebServer/Documents/gitlist"
and changed the following lines in /etc/apache2/httpd.conf


LoadModule php5_module libexec/apache2/libphp5.so
<Directory "/Library/WebServer/Documents/gitlist">
AllowOverride All
</Directory> 

... everything works beautifully and I can confirm that addresses such as 
http://localhost/gitlist/composer.json
should not be displayed.

**Comment by klaussilveira** [comment] 2015-02-06 15:50
The reason we deployed `index.php` to the project root was to make GitList easier to use for non-developers. Most people are used to deploying PHP applications by just dropping the app folder to Apache's root. 

Some large refactoring is going to take place soon and i intend to rethink this approach. Maybe it's the responsibility of the packager to do this (making a symlink or something like this). Therefore, i'm marking this as todo.

**Comment by garygreen** [comment] 2015-02-06 16:02
I think it's a pretty common enough practice to have a `public` and main `app/src` folder in most packages, and to have these separate. If they're not, you risk security implications. Symlinking really isn't a good solution because your burdening those who want to make their app secure.

Glad to see your looking to rethink the approach :smile:

**Comment by klaussilveira** [comment] 2015-02-06 16:59
To us. And most developers. But not for people that are used to installing old PHP applications like Wordpress and Moodle. 

This decision made sense 2 years ago. Now, we have to rethink about it since more and more popular PHP applications are adopting this approach. Therefore, people will understand the advantages instead of just claiming "Too difficult to install!".

**Closed** 2019-05-09 00:35 UTC
Labels: enhancement
