### ISSUE TITLE
CSS not loading for Themes

### ISSUE THREAD

**Issue by E-t-z** [klaussilveira/gitlist#779] opened 2018-05-22 19:42 UTC
After update from 0.7.0 to 1.0.0, themes CSS is not loading anymore.
Neither for Default or Bootstrap3 theme, not yet sure why, as all config.ini and .htaccess as stayed the same.

**Comment by alehaa** [comment] 2018-05-22 19:44
Is this a duplicate of #775?

**Comment by E-t-z** [comment] 2018-05-22 19:48
Yep, most likely:

`

<head>
--
  | <meta charset="UTF-8" />
  | <title>GitList</title>
  | <meta name="viewport" content="width=device-width, initial-scale=1">
  | <link rel="stylesheet" type="text/css" href="/themes/bootstrap3/css/style.css">
  | <link rel="stylesheet" type="text/css" href="/themes/bootstrap3/css/fontawesome.css">
  | <link rel="stylesheet" type="text/css" href="/themes/bootstrap3/css/gitgraph.css">
  | <link rel="shortcut icon" type="image/png" href="/themes/bootstrap3/img/favicon.png" />
  | 
  | </head>

`

**Comment by E-t-z** [comment] 2018-05-22 20:00
Applied #776 manually and it is fixed.

**Closed** 2018-05-22 20:00 UTC

**Comment by E-t-z** [comment] 2018-05-22 20:08
One sidenote though, this seems to be broken now, if 
`ssh_host = '' ; host to use for cloning via HTTP (default: none => uses gitlist web host)`
is left empty on config.ini, then clone url is broken for ssh, there is no host part in url.

**Comment by alehaa** [comment] 2018-05-22 20:11
@E-t-z can you move this comment to #777 please?

**Comment by E-t-z** [comment] 2018-05-22 20:19
Not sure how to move it, but I can comment there.
