### ISSUE TITLE
RuntimeException: The process has been signaled with signal "5". (OS X 10.6.8/MAMP)

### ISSUE THREAD

**Issue by dodginess** [klaussilveira/gitlist#664] opened 2016-05-18 22:10 UTC
After installing gitlist and trying to browse a local repository that I'd just created, the following error message was displayed:

```
RuntimeException: The process has been signaled with signal "5".
 
in /Applications/MAMP/htdocs/gitlist/vendor/symfony/process/Symfony/Component/Process/Process.php line 332
at Process->wait() in /Applications/MAMP/htdocs/gitlist/vendor/symfony/process/Symfony/Component/Process/Process.php line 200
at Process->run() in /Applications/MAMP/htdocs/gitlist/vendor/klaussilveira/gitter/lib/Gitter/Client.php line 71
at Client->run(object(Repository), 'branch') in /Applications/MAMP/htdocs/gitlist/vendor/klaussilveira/gitter/lib/Gitter/Repository.php line 164
at Repository->getBranches() in /Applications/MAMP/htdocs/gitlist/src/GitList/Util/Routing.php line 44
at Routing->parseCommitishPathParam('master', 'test') in /Applications/MAMP/htdocs/gitlist/src/GitList/Controller/TreeController.php line 22
at GitList\Controller{closure}('test', 'master')
at call_user_func_array(object(Closure), array('test', 'master')) in /Applications/MAMP/htdocs/gitlist/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php line 126
at HttpKernel->handleRaw(object(Request), '1') in /Applications/MAMP/htdocs/gitlist/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php line 66
at HttpKernel->handle(object(Request), '1', true) in /Applications/MAMP/htdocs/gitlist/vendor/silex/silex/src/Silex/Application.php line 538
at Application->handle(object(Request)) in /Applications/MAMP/htdocs/gitlist/vendor/silex/silex/src/Silex/Application.php line 515
at Application->run() in /Applications/MAMP/htdocs/gitlist/index.php line 32
```

This appears to be an issue with Symfony and the `DYLD_LIBRARY_PATH` set by MAMP. To confirm what this was set to I used this code:

```php
var_dump(getenv('DYLD_LIBRARY_PATH'));
```
```
string(31) "/Applications/MAMP/Library/lib:"
```

If I edit `/gitlist/vendor/symfony/process/Symfony/Component/Process/Process.php` and add

```php
putenv("DYLD_LIBRARY_PATH=''");
```

at the start of the script (after the namespace and use declarations) the error message isn't displayed and I can browse the repository without any issues.

My server configuration is OS 10.6.8, MAMP 1.9.6 and PHP 5.3.5.

**Comment by alehaa** [comment] 2017-08-27 19:47
Seems to be a duplicate of #512.

**Closed by alehaa** 2017-08-27 19:47 UTC
Labels: duplicate
