### ISSUE TITLE
PHP 7.2.5 gives  Cannot use Object as class name

### ISSUE THREAD

**Issue by ArthurBorsboom** [klaussilveira/gitlist#782] opened 2018-05-27 20:17 UTC
Getting this error with PHP 7.2.5

Fatal error: Cannot use 'Object' as class name as it is reserved in /home/git/public_html/gitlist/vendor/klaussilveira/gitter/lib/Gitter/Model/Object.php on line 14

**Comment by alehaa** [comment] 2018-05-28 08:50
These files belong to Gitter, which has [its own repository](https://github.com/klaussilveira/gitter). Also a duplicate of #765.

**Closed by alehaa** 2018-05-28 08:50 UTC

**Comment by alehaa** [comment] 2018-05-29 20:17
Nope, I'm just involved in this project yet. However, [there's an issue filled](https://github.com/klaussilveira/gitter/issues/62).

If v1.0.0 isn't working for you, it'll be nice to file issues for the related bugs, *if they haven't been filed yet*. v4.0.0 isn't supported anymore as it's **way** to old.

**Comment by cedx** [comment] 2018-05-31 11:53
Thanks for your answer. The main issue, for me, is really the lack of PHP 7 support from Gitter.
(it doesn't matter finally: I fixed this issue, and rolled my own version... https://git.belin.io)

GitList is a great product. I hope that its development will carry on.
