### ISSUE TITLE
Support git's .mailmap

### ISSUE THREAD

**Issue by jcbwlkr** [klaussilveira/gitlist#530] opened 2014-11-12 17:45 UTC
In one of my projects there is a developer who has commits under multiple name/emails
- `susan@company.com`
- `susan@localhost`
- `sue@company.com` and so on

We have a `.mailmap` file in the application which defines that all of these are really the same person. When I run `git shortlog -s` all commits from that developer are combined.

A similar behavior might be desirable in the `/repo/stats/branch` view

**Comment by cxw42** [comment] 2019-09-23 18:54
In my tests, mailmaps work with 1.0.2 - looks like the fix was in #563.  I believe this can be closed as duplicate of #562, and resolved.

**Closed** 2019-09-23 19:01 UTC
Labels: feature
