### ISSUE TITLE
Full path not being displayed for repositories nested in more than one folder

### ISSUE THREAD

**Issue by mmaszkiewicz** [klaussilveira/gitlist#521] opened 2014-10-17 11:02 UTC
If a repo is nested in more than just one folder, example: `/firstfolder/secondfolder/repofolder`, the first folder won't be displayed (list view or repo details view)

**Comment by alehaa** [comment] 2018-06-15 04:20
Seems to be a duplicate of #391, which got a PR merged now in #788.

**Closed by alehaa** 2018-06-15 04:20 UTC
